DELETE http://localhost:3001/api/persons/60bdf6bc590346cc88f44602

###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Shilpa", "number": "93939393"
}

###
GET http://localhost:3001/api/persons/60bb96bf003242aeb94559d4

###
Put http://localhost:3001/api/persons/60c075069954b44a8d8a1807
Content-Type: application/json

{
    "name": "Nischhal", "number": "383-225"
}