DELETE http://localhost:3001/api/persons/60bdf6bc590346cc88f44602

###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Nischhal", "number": ""
}

###
GET http://localhost:3001/api/persons/60bb969b003242aeb94559d2